=== tanaym42/tanaym42.github.io/restaurants.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--author: tanay mahindru-->
<!--INFO 202: Assignment 4-->

<!ELEMENT restaurants(id, name, cuisine, city, open, close)>

<!ELEMENT id        (#PCDATA)>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT cuisine   (#PCDATA)>
<!ELEMENT city      (#PCDATA)>
<!ELEMENT open      (#PCDATA)>
<!ELEMENT close     (#PCDATA)>

=== tanaym42/tanaym42.github.io/restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--author: tanay mahindru-->
<!--INFO 202: Assignment 4-->

<!DOCTYPE restaurants SYSTEM "restaurants.dtd">

<restaurants>
	<id>0</id>
	<name>Kabana</name>
	<cuisine>Indian</cuisine>
	<city>Berkeley</city>
	<open>12pm</open>
	<close>9pm</close>
</restaurants>
<restaurants>
	<id>1</id>
	<name>Cheeseboard</name>
	<cuisine>Italian</cuisine>
	<city>Berkeley</city>
	<open>11am</open>
	<close>8pm</close>
</restaurants>
<restaurants>
	<id>2</id>
	<name>The Butcher's Son</name>
	<cuisine>American</cuisine>
	<city>Berkeley</city>
	<open>9am</open>
	<close>3pm</close>
</restaurants>
